-- J1 : schéma géré par Flyway (Hibernate en ddl-auto=validate, plus de create-drop).

CREATE TABLE aircraft
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration VARCHAR(255) NOT NULL,
    model        VARCHAR(255) NOT NULL,
    flight_hours DOUBLE PRECISION NOT NULL,
    CONSTRAINT uk_aircraft_registration UNIQUE (registration)
);

CREATE TABLE flight_reading
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aircraft_id     BIGINT NOT NULL,
    recorded_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    cycles          INTEGER NOT NULL,
    max_load_factor DOUBLE PRECISION NOT NULL,
    flight_hours    DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_flight_reading_aircraft FOREIGN KEY (aircraft_id) REFERENCES aircraft (id) ON DELETE CASCADE
);

CREATE INDEX idx_flight_reading_aircraft_id ON flight_reading (aircraft_id);
