-- J2 : état de fatigue calculé par appareil, recalculé par le job Spring Batch
-- (voir dev.ynzi.fatiguetracker.fatigue). Une ligne par appareil, mise à jour en
-- upsert à chaque exécution du job (jamais d'historique conservé ici : le
-- calcul est déterministe, rejouable à tout instant à partir des relevés).

CREATE TABLE fatigue_status
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aircraft_id        BIGINT NOT NULL,
    fatigue_index      DOUBLE PRECISION NOT NULL,
    readings_count     INTEGER NOT NULL,
    computed_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    maintenance_alert  BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_fatigue_status_aircraft_id UNIQUE (aircraft_id),
    CONSTRAINT fk_fatigue_status_aircraft FOREIGN KEY (aircraft_id) REFERENCES aircraft (id) ON DELETE CASCADE
);
