-- J3 : comptes applicatifs (Spring Security). Deux comptes de DÉMONSTRATION sont
-- seedés ici avec des hash BCrypt de mots de passe publics et documentés dans le
-- README (jamais de vrai secret dans une migration Flyway versionnée) :
--   demo.viewer / viewer123  (rôle VIEWER)
--   demo.maint  / maint123   (rôle MAINT)

CREATE TABLE app_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(20)  NOT NULL,
    CONSTRAINT uk_app_user_username UNIQUE (username)
);

INSERT INTO app_user (username, password, role)
VALUES ('demo.viewer', '$2a$10$rQvhwKxeOafUmVPbSjF2C.OgR3047LARiaPpYB7geEUnILZDw42hC', 'VIEWER'),
       ('demo.maint', '$2a$10$Fysz7FwQwQyNGpGrBbnnu.Cn.VYUBhEfoT4wtJKNb/d6oiIGoEeUK', 'MAINT');
